import 'surah_model.dart';

class StaticSurahData {
  static final List<SurahModel> surahs = [
    SurahModel(
      id: 1,
      name: "Al-Fatihah",
      translatedName: "The Opener",
      versesCount: 7,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 2,
      name: "Al-Baqarah",
      translatedName: "The Cow",
      versesCount: 286,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 3,
      name: "Ali 'Imran",
      translatedName: "Family of Imran",
      versesCount: 200,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 4,
      name: "An-Nisa",
      translatedName: "The Women",
      versesCount: 176,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 5,
      name: "Al-Ma'idah",
      translatedName: "The Table Spread",
      versesCount: 120,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 6,
      name: "Al-An'am",
      translatedName: "The Cattle",
      versesCount: 165,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 7,
      name: "Al-A'raf",
      translatedName: "The Heights",
      versesCount: 206,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 8,
      name: "Al-Anfal",
      translatedName: "The Spoils of War",
      versesCount: 75,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 9,
      name: "At-Tawbah",
      translatedName: "The Repentance",
      versesCount: 129,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 10,
      name: "Yunus",
      translatedName: "Jonah",
      versesCount: 109,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 11,
      name: "Hud",
      translatedName: "Hud",
      versesCount: 123,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 12,
      name: "Yusuf",
      translatedName: "Joseph",
      versesCount: 111,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 13,
      name: "Ar-Ra'd",
      translatedName: "The Thunder",
      versesCount: 43,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 14,
      name: "Ibrahim",
      translatedName: "Abraham",
      versesCount: 52,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 15,
      name: "Al-Hijr",
      translatedName: "The Rocky Tract",
      versesCount: 99,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 16,
      name: "An-Nahl",
      translatedName: "The Bee",
      versesCount: 128,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 17,
      name: "Al-Isra",
      translatedName: "The Night Journey",
      versesCount: 111,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 18,
      name: "Al-Kahf",
      translatedName: "The Cave",
      versesCount: 110,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 19,
      name: "Maryam",
      translatedName: "Mary",
      versesCount: 98,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 20,
      name: "Ta-Ha",
      translatedName: "Ta-Ha",
      versesCount: 135,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 21,
      name: "Al-Anbiya",
      translatedName: "The Prophets",
      versesCount: 112,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 22,
      name: "Al-Hajj",
      translatedName: "The Pilgrimage",
      versesCount: 78,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 23,
      name: "Al-Mu'minun",
      translatedName: "The Believers",
      versesCount: 118,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 24,
      name: "An-Nur",
      translatedName: "The Light",
      versesCount: 64,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 25,
      name: "Al-Furqan",
      translatedName: "The Criterion",
      versesCount: 77,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 26,
      name: "Ash-Shu'ara",
      translatedName: "The Poets",
      versesCount: 227,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 27,
      name: "An-Naml",
      translatedName: "The Ant",
      versesCount: 93,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 28,
      name: "Al-Qasas",
      translatedName: "The Stories",
      versesCount: 88,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 29,
      name: "Al-'Ankabut",
      translatedName: "The Spider",
      versesCount: 69,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 30,
      name: "Ar-Rum",
      translatedName: "The Romans",
      versesCount: 60,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 31,
      name: "Luqman",
      translatedName: "Luqman",
      versesCount: 34,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 32,
      name: "As-Sajdah",
      translatedName: "The Prostration",
      versesCount: 30,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 33,
      name: "Al-Ahzab",
      translatedName: "The Combined Forces",
      versesCount: 73,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 34,
      name: "Saba",
      translatedName: "Sheba",
      versesCount: 54,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 35,
      name: "Fatir",
      translatedName: "Originator",
      versesCount: 45,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 36,
      name: "Ya-Sin",
      translatedName: "Ya Sin",
      versesCount: 83,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 37,
      name: "As-Saffat",
      translatedName: "Those who set the Ranks",
      versesCount: 182,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 38,
      name: "Sad",
      translatedName: "The Letter \"Saad\"",
      versesCount: 88,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 39,
      name: "Az-Zumar",
      translatedName: "The Troops",
      versesCount: 75,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 40,
      name: "Ghafir",
      translatedName: "The Forgiver",
      versesCount: 85,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 41,
      name: "Fussilat",
      translatedName: "Explained in Detail",
      versesCount: 54,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 42,
      name: "Ash-Shura",
      translatedName: "The Consultation",
      versesCount: 53,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 43,
      name: "Az-Zukhruf",
      translatedName: "The Ornaments of Gold",
      versesCount: 89,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 44,
      name: "Ad-Dukhan",
      translatedName: "The Smoke",
      versesCount: 59,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 45,
      name: "Al-Jathiyah",
      translatedName: "The Crouching",
      versesCount: 37,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 46,
      name: "Al-Ahqaf",
      translatedName: "The Wind-Curved Sandhills",
      versesCount: 35,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 47,
      name: "Muhammad",
      translatedName: "Muhammad",
      versesCount: 38,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 48,
      name: "Al-Fath",
      translatedName: "The Victory",
      versesCount: 29,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 49,
      name: "Al-Hujurat",
      translatedName: "The Rooms",
      versesCount: 18,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 50,
      name: "Qaf",
      translatedName: "The Letter \"Qaf\"",
      versesCount: 45,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 51,
      name: "Ad-Dhariyat",
      translatedName: "The Winnowing Winds",
      versesCount: 60,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 52,
      name: "At-Tur",
      translatedName: "The Mount",
      versesCount: 49,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 53,
      name: "An-Najm",
      translatedName: "The Star",
      versesCount: 62,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 54,
      name: "Al-Qamar",
      translatedName: "The Moon",
      versesCount: 55,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 55,
      name: "Ar-Rahman",
      translatedName: "The Beneficent",
      versesCount: 78,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 56,
      name: "Al-Waqi'ah",
      translatedName: "The Inevitable",
      versesCount: 96,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 57,
      name: "Al-Hadid",
      translatedName: "The Iron",
      versesCount: 29,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 58,
      name: "Al-Mujadila",
      translatedName: "The Pleading Woman",
      versesCount: 22,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 59,
      name: "Al-Hashr",
      translatedName: "The Exile",
      versesCount: 24,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 60,
      name: "Al-Mumtahanah",
      translatedName: "She that is to be examined",
      versesCount: 13,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 61,
      name: "As-Saff",
      translatedName: "The Ranks",
      versesCount: 14,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 62,
      name: "Al-Jumu'ah",
      translatedName: "The Congregation, Friday",
      versesCount: 11,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 63,
      name: "Al-Munafiqun",
      translatedName: "The Hypocrites",
      versesCount: 11,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 64,
      name: "At-Taghabun",
      translatedName: "The Mutual Disillusion",
      versesCount: 18,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 65,
      name: "At-Talaq",
      translatedName: "The Divorce",
      versesCount: 12,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 66,
      name: "At-Tahrim",
      translatedName: "The Prohibition",
      versesCount: 12,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 67,
      name: "Al-Mulk",
      translatedName: "The Sovereignty",
      versesCount: 30,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 68,
      name: "Al-Qalam",
      translatedName: "The Pen",
      versesCount: 52,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 69,
      name: "Al-Haqqah",
      translatedName: "The Reality",
      versesCount: 52,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 70,
      name: "Al-Ma'arij",
      translatedName: "The Ascending Stairways",
      versesCount: 44,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 71,
      name: "Nuh",
      translatedName: "Noah",
      versesCount: 28,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 72,
      name: "Al-Jinn",
      translatedName: "The Jinn",
      versesCount: 28,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 73,
      name: "Al-Muzzammil",
      translatedName: "The Enshrouded One",
      versesCount: 20,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 74,
      name: "Al-Muddaththir",
      translatedName: "The Cloaked One",
      versesCount: 56,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 75,
      name: "Al-Qiyamah",
      translatedName: "The Resurrection",
      versesCount: 40,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 76,
      name: "Al-Insan",
      translatedName: "The Man",
      versesCount: 31,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 77,
      name: "Al-Mursalat",
      translatedName: "The Emissaries",
      versesCount: 50,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 78,
      name: "An-Naba",
      translatedName: "The Tidings",
      versesCount: 40,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 79,
      name: "An-Nazi'at",
      translatedName: "Those who drag forth",
      versesCount: 46,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 80,
      name: "'Abasa",
      translatedName: "He Frowned",
      versesCount: 42,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 81,
      name: "At-Takwir",
      translatedName: "The Overthrowing",
      versesCount: 29,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 82,
      name: "Al-Infitar",
      translatedName: "The Cleaving",
      versesCount: 19,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 83,
      name: "Al-Mutaffifin",
      translatedName: "The Defrauding",
      versesCount: 36,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 84,
      name: "Al-Inshiqaq",
      translatedName: "The Sundering",
      versesCount: 25,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 85,
      name: "Al-Buruj",
      translatedName: "The Mansions of the Stars",
      versesCount: 22,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 86,
      name: "At-Tariq",
      translatedName: "The Nightcommer",
      versesCount: 17,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 87,
      name: "Al-A'la",
      translatedName: "The Most High",
      versesCount: 19,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 88,
      name: "Al-Ghashiyah",
      translatedName: "The Overwhelming",
      versesCount: 26,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 89,
      name: "Al-Fajr",
      translatedName: "The Dawn",
      versesCount: 30,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 90,
      name: "Al-Balad",
      translatedName: "The City",
      versesCount: 20,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 91,
      name: "Ash-Shams",
      translatedName: "The Sun",
      versesCount: 15,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 92,
      name: "Al-Lail",
      translatedName: "The Night",
      versesCount: 21,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 93,
      name: "Ad-Duha",
      translatedName: "The Morning Hours",
      versesCount: 11,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 94,
      name: "Ash-Sharh",
      translatedName: "The Relief",
      versesCount: 8,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 95,
      name: "At-Tin",
      translatedName: "The Fig",
      versesCount: 8,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 96,
      name: "Al-'Alaq",
      translatedName: "The Clot",
      versesCount: 19,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 97,
      name: "Al-Qadr",
      translatedName: "The Power",
      versesCount: 5,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 98,
      name: "Al-Bayyinah",
      translatedName: "The Clear Proof",
      versesCount: 8,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 99,
      name: "Az-Zalzalah",
      translatedName: "The Earthquake",
      versesCount: 8,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 100,
      name: "Al-'Adiyat",
      translatedName: "The Courser",
      versesCount: 11,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 101,
      name: "Al-Qari'ah",
      translatedName: "The Calamity",
      versesCount: 11,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 102,
      name: "At-Takathur",
      translatedName: "The Rivalry in world increase",
      versesCount: 8,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 103,
      name: "Al-'Asr",
      translatedName: "The Declining Day",
      versesCount: 3,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 104,
      name: "Al-Humazah",
      translatedName: "The Traducer",
      versesCount: 9,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 105,
      name: "Al-Fil",
      translatedName: "The Elephant",
      versesCount: 5,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 106,
      name: "Quraish",
      translatedName: "Quraish",
      versesCount: 4,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 107,
      name: "Al-Ma'un",
      translatedName: "The Small Kindnesses",
      versesCount: 7,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 108,
      name: "Al-Kauthar",
      translatedName: "The Abundance",
      versesCount: 3,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 109,
      name: "Al-Kafirun",
      translatedName: "The Disbelievers",
      versesCount: 6,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 110,
      name: "An-Nasr",
      translatedName: "The Divine Support",
      versesCount: 3,
      revelationPlace: "MADINAH",
    ),
    SurahModel(
      id: 111,
      name: "Al-Masad",
      translatedName: "The Palm Fiber",
      versesCount: 5,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 112,
      name: "Al-Ikhlas",
      translatedName: "The Sincerity",
      versesCount: 4,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 113,
      name: "Al-Falaq",
      translatedName: "The Daybreak",
      versesCount: 5,
      revelationPlace: "MAKKAH",
    ),
    SurahModel(
      id: 114,
      name: "An-Nas",
      translatedName: "The Mankind",
      versesCount: 6,
      revelationPlace: "MAKKAH",
    ),
  ];
}
